# Generated by Django 4.2.3 on 2023-07-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('abstract', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=250)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tg', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('researcher', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('abstract', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=250)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField(max_length=250)),
                ('tg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lensAcademia.tg')),
            ],
        ),
    ]
