# Generated by Django 4.2.3 on 2023-07-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensAcademia', '0002_alter_author_id_alter_keyword_id_alter_keyword_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='researcher',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='researchers',
            field=models.ManyToManyField(to='lensAcademia.author'),
        ),
    ]
