# Generated by Django 4.2.3 on 2023-07-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensAcademia', '0003_remove_author_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tg',
            name='tg',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
