# Generated by Django 4.2.3 on 2023-07-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensAcademia', '0004_alter_tg_tg'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='keywords',
            field=models.ManyToManyField(to='lensAcademia.keyword'),
        ),
    ]
