# Generated by Django 4.2.3 on 2023-07-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lensAcademia', '0005_researchpaper_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='tgs',
            field=models.ManyToManyField(related_name='research_papers_tgs', to='lensAcademia.tg'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='keywords',
            field=models.ManyToManyField(related_name='research_papers', to='lensAcademia.keyword'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='researchers',
            field=models.ManyToManyField(related_name='research_papers', to='lensAcademia.author'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='tg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_papers_tg', to='lensAcademia.tg'),
        ),
    ]
