# Generated by Django 4.2.3 on 2023-07-25 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lensAcademia', '0006_researchpaper_tgs_alter_researchpaper_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='tgs',
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='keywords',
            field=models.ManyToManyField(to='lensAcademia.keyword'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='researchers',
            field=models.ManyToManyField(to='lensAcademia.author'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='tg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lensAcademia.tg'),
        ),
    ]
