# Generated by Django 4.2.3 on 2023-07-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lensAcademia', '0007_remove_researchpaper_tgs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
    ]
