# Generated by Django 4.2.3 on 2023-07-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lensAcademia', '0008_remove_author_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='website',
        ),
    ]
