# Generated by Django 4.2.3 on 2023-07-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensAcademia', '0010_author_research_papers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='abstract',
            field=models.CharField(max_length=5000),
        ),
    ]
