# Generated by Django 4.2.3 on 2023-07-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensAcademia', '0011_alter_researchpaper_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='research_papers',
            field=models.ManyToManyField(to='lensAcademia.researchpaper'),
        ),
    ]
